services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

